### ISSUE TITLE
Playlist order not respected properly

### ISSUE THREAD

**Issue by thaihugo** [memen45/SubMusic#15]
Hi,
Thanks for your program. I was using one of the first versions and recently updated to the latest one using garmin connect.
I also decided to update my playlist to new ones.
On my new sync, the playlist order is not respected. It is not fully random, but some tracks are mixed and I have at most 2 or 3 tracks that do respect the playlist order.
Of course, if it was just mp3 sync, I would consider a bad tagging process (although all my tracks are perfectly tagged, including play order). But as this is a playlist, I don't understand the reason why it would change the order.

setup is using Airsonic on raspberry pi 3b+:

10.6.2-RELEASE – 3 may 2020
--
Server | Apache Tomcat/8.5.51, java 11.0.9.1, Linux (142,6 MB / 268,8 MB)

The setup didn't change between version when syncing was in the proper order.

please advice for any test or logs you might need.

thanks

**Comment by memen45** [comment]
As far as I could find, there is no way to retrieve the playlist songs in a specific order at the Subsonic API endpoint [Subsonic Docs](http://www.subsonic.org/pages/api.jsp#getPlaylist) nor at the Ampache API endpoint [Ampache Docs](http://ampache.org/api/api-json-methods#playlist_songs). Therefore ordering is currently fixed and depending on the ordering that is received from the server.

In case you have changed the playlist on the server, the order may not be reflected exactly, as new songs will be appended to the end of the song list instead of inserted in the right order. Is this reflecting your situation? If so, this is something I can address in a future update.

You can manually fix the order by removing the playlist, perform a full sync, then add the playlist again. This way the order will match the server's order again.

**Comment by thaihugo** [comment]
Thanks for your help.I tried to test a few things to give you more info. I added a new playlist to see the behaviour. I've noted the following thinks:

- the watch is asking for a connection to garmin connect now to select playlists (104 "BLE CONNECTION_UNAVAILABLE". The previous versions could do the direct WIFI connection to my server to select them. I can still sync using wifi.
- The new list was added quickly but asked for a sync to play. I could however launch it and it was playing in the correct order. As soon as the sync was done, the order was not correct anymore.
- The wrong order is the same for any playlist with the same album.
- Going to the "songs" item in the "choose playlist" menu gives the proper song order. Launching the playlist from this song menu does not give the proper order but the wrong (same) one.
- I do not have the "shuffle" or "repeat" parameter activated

I'm surprised the app is seeing the proper order in the song list but doesn't play it like this. I will try to test different albums combinations and report if I have more information.

**Comment by memen45** [comment]
Thanks a lot for your detailed info! What do you mean with 

>     * I could however launch it and it was playing in the correct order

How were you able to play it if it was not synced yet?

I think I have an idea of the problem based on your feedback. I think the songs are ordered by song id. Unfortunately, it is probably difficult for you to check this? Anyways, I will take this into account for the next update and fix it!

**Comment by thaihugo** [comment]
It mystified me too. My guess is either because the songs were existing in the cache because they where already synced for another playlist, or it was downloading the songs at the same time.
I can try to check this song id parameter. Are you talking about the mp3 tag, or about a subsonic protocol parameter?

**Comment by memen45** [comment]
The id is provided when retrieving the song list from subsonic. The ids are used by SubMusic app to keep everything synchronized. In the music player however, the songs are loaded by id in <key, value> pairs as <id, internal link>. Then when played, the keys are requested for all the pairs, however, they are probably returned in alphabetical order (or increasing, if the id's are integers). The order of playing is then determined by the song id, rather than the original order of the playlist.

**Comment by memen45** [comment]
Just now I uploaded a new version to the Connect IQ app store (v0.1.3-delta) which includes the fix for ordering. I made sure that the order as it is received from the server is used as the local ordering as well. Hope it solves your problem, let me know if it does!

**Comment by thaihugo** [comment]
It works. The old and new playlists are corrected immediately without sync.
Thanks for the fast update!
