### ISSUE TITLE
Issue with auto sync

### ISSUE THREAD

**Issue by shady2k** [memen45/SubMusic#17]
I use ampache backend with nextcloud. When I charge my watch, system start auto music synchronization. It starts but never ends, sync job running endlessly, always at 0%. And there is one way - manually cancel sync. Sometimes after this sync songs not playing. I see it in the list, but nothing plays.
Version: 0.1.3-delta, new version still not available in store.

Logs from my nextcloud instance:
```
[19/Jan/2021:22:46:24 +0300] "GET /index.php/apps/music/ampache/server/json.server.php?action=playlist&filter=3&auth=XXX HTTP/1.0" 200 89 "-" "Garmin Forerunner 645 Music/7.0"
[19/Jan/2021:22:46:24 +0300] "GET /index.php/apps/music/ampache/server/json.server.php?limit=20&action=playlist_songs&filter=3&offset=0&auth=XXX HTTP/1.0" 200 1299 "-" "Garmin Forerunner 645 Music/7.0"
```

**Comment by memen45** [comment]
Yes I got another report about this as well. I hope this is fixed with the new 0.1.4-echo update as well. Let me know your findings when you have updated.

**Comment by bananer** [comment]
I had the same issue of auto sync being stuck at 0% and I think it went away after upgrading to Nextcloud 20.0.5

**Comment by memen45** [comment]
Ah yes, I missed that you are using ampache on nextcloud. There was a bug with ampache on version 20, which is fixed with version 20.0.5 owncloud/music#811. What version of nextcloud are you on?

However, the auto sync 0% bug also occurs with different backends and thus I do not think it is related to the nextcloud version. Actually it is related to a Garmin bug which I have reported [on the Garmin forum](https://forums.garmin.com/developer/connect-iq/i/bug-reports/bug-media-communications-syncdelegate-blocks-charging). A workaround is included in the SubMusic v0.1.4-echo update, however, since I do not have a device showing the bug, I am not sure whether it is fixed or not.

**Comment by shady2k** [comment]
Thanks, update to Nextcloud version 20.0.5 and Music app to v0.17.3 fixed issue with sync.

**Comment by memen45** [comment]
Do you know whether the cause is the nextcloud update or the SubMusic update? I had some questions through email as well regarding the same problem, so if you know the cause I can link this to those users as well. Thanks in advance!

**Comment by shady2k** [comment]
Likely it's SubMusic update. Before Nextcloud update I had Beta channel Nextcloud 21 beta 4 because stable release weren't work. Now I did downgrade to stable channel.

**Comment by memen45** [comment]
Great, thanks a lot for your feedback!
