### ISSUE TITLE
Network Request Timed Out Errors When Fetching Playlists Or Testing Server

### ISSUE THREAD

**Issue by MochaMage** [memen45/SubMusic#19]
Hi, I updated the app a few weeks ago but when I try to fetch playlists from my server, I'm getting the Timed Out error screen. I've confirmed that my details and credentials are correct, as I am not seeing the same error when I Sync; In that case, my Garmin Vivoactive 3 Music connects to my WiFi and shows that the watch has successfully synced. The Timeouts are being shown even though there appears to be no attempt to connect to my WiFi network. I've tried removing all settings, deleting the application and reinstalling with no luck.

**Comment by memen45** [comment]
Do you access the 'Sync menu' through the Playback menu or through the watch settings->music providers->sync? The latter case might work better as wifi connection is made before the menu is opened.

**Comment by opencode00** [comment]
Hi, my problem is similar, the watch is looping  forever while it show a message "Sincronizando". The watch found the wifi connection and then loop...
I understand the API key in config correspond tona user's password, right?
Thank you for advanced.

**Comment by victor-dementiev** [comment]
@opencode00 The API key is the password for your server. 
Hope this answer helps you.

**Comment by MochaMage** [comment]
@memen45 I tried that way as well but got the same network time out error as when going through the playback menu. For some reason, the same error also comes up when I open the "Show Server Setting" menu. I am able to use the Sync option and the watch connects to WiFi and a success message is given but fetching playlists will yield the timeout error with no WiFi connection attempted.

**Comment by memen45** [comment]
Sorry for not coming back to you soon. Do you still have the problem? Could you provide more details on your setup or maybe provide me some temporary login on your server through the Garmin Connect IQ app store "contact developer" option?

**Comment by memen45** [comment]
Closing the issue with the following:

A similar [report](https://forums.garmin.com/developer/connect-iq/f/discussion/166139/error--300) on the Garmin developer forum. It seems like some devices are requiring https connection. This could be due to the Garmin Connect Mobile version and operating system (iOS is more strict than Android).

The documentation states a -1001 error indicates https requirements, but as the report states, in practice it results in a -300 network timeout.

Unfortunately, as a developer I cannot circumvent these limitations. I would recommend using https on your site if possible. I should note that self-signed certificates are also not supported on Garmin watches.

_Originally posted by @memen45 in https://github.com/memen45/SubMusic/issues/22#issuecomment-809971062_

If you are able to, please report the GCM version and phone operating system you are working with and also whether the url is local, http or https. This could be very helpful for me to possibly report it as a bug to Garmin.

**Comment by MochaMage** [comment]
Hey memen, the phone OS is Android 11 and the device is the Vivoactive 3 Music with software version 6.00 and Connect IQ 3.2.0. The URL I was trying to connect to is http but I also tried out setting up my server to use https but I guess the self-signed cert issue is what's stopped it from working with yet another -300. Let me know if you need more details for the bug report to Garmin.

**Comment by memen45** [comment]
Thanks for your feedback. Did you try connecting to an https server with certificates signed by a CA? Could you share your findings on that?
