### ISSUE TITLE
Problem connecting to Airsonic

### ISSUE THREAD

**Issue by thaihugo** [memen45/SubMusic#21]
Hi,

i've been using SubMusic with Airsonic from https://github.com/airsonic/airsonic.github.io
I use the latest standalone version from last may.

My last working sync was in January, and was working perfectly. However I cannot make the latest 0.16-golf version to sync.
The test server function gives HTTP error 500. I can see by tracing the network that garmin connect on my iOS does connect, but it gets this error message from Airsonic.

The sync action loops endlessly. it displays "Syncing" with no variation
The playlist function gives "HTTP error 500".

I've tried reinstalling the server completely but it didn't help. I also noticed that I can only start the sync without any BT connection to the iOS device. All other tests requires that BT is connected.

is there something that has been changed lately that could break the sync?
Is is possible for my to get an older version to install manually on my Garmin Fenix 6 to see if it works?

Watch: Garmin Fenix Saphire 6 13.30
Submusic 0.16-golf
IOS 14.3, latest garmin connect
Airsonic latest version (April-may 2020)

Please advise for any log or test needed

thanks

**Comment by memen45** [comment]
Http Error 500 would indicate a server error. Did you check the logs on your server? Are you able to access everything normally from your server?

Also if you can track the traffic, can you try to copy the url and try it from your browser and see the result?

Refactor of the sync engine was implemented since v0.0.19-tau [20-11-2020], and since then only minor changes. This update may have introduced this bluetooth dependent behaviour. It is due to the implementation of the Garmin Connect SDK, so either choice of Garmin or a bug.

**Comment by thaihugo** [comment]
Got my mistake. It is a trailing / in the url that must be removed (ip:8080/airsonic not ip:8080/airsonic/)
Sorry to have bothered you and thank you for your help!

**Comment by memen45** [comment]
Is it working for you with the port number in the url? As far as I understood, any other port than 80 or 443 is not supported by the watch.

**Comment by thaihugo** [comment]
It does. However, it act strangely: it requests a wifi connection where the ip adress is valid, but it  download at bluetooth speed. It seems to funnel back through the garmin connect Bt connection once the connection is established. 
Previously, it was using wifi directly and was syncing in a few minutes. Maybe the non standard port causes this behavior
