### ISSUE TITLE
No password field

### ISSUE THREAD

**Issue by deljones** [memen45/SubMusic#27]
Hello

there is a field for web server address, username and API key but no password ?

With thanks

dj

**Comment by memen45** [comment]
The API key is the password. 

It is named API key because some servers support a separate access key for external apps to login. This way you don't have to fill in your own personal password in other apps. As far as I know, only Nextcloud offers this option, so if you do not use Nextcloud, your password should be the API key.

**Comment by memen45** [comment]
If you still have questions, feel free to comment or send me an email through 'Contact developer' option in Connect IQ!
