### ISSUE TITLE
Can't sync with SubMusic 0.1.19 and Ampache (4 and 5)

### ISSUE THREAD

**Issue by lemieuxl** [memen45/SubMusic#34]
Since the update to SubMusic 0.1.19, I'm unable to sync any music to my Venu 2.

At first, I wasn't able to sync my song playlist using Ampache 4. I always got a "Media error occurred". So I installed Ampache 5.

I get a `ApiError: BADRESPONSE` when I try to select a playlist. I get the same error when trying to test the server. "Show server settings" shows the correct URL and the Ampache version.

**Comment by memen45** [comment]
Thanks for your report. I checked the API specs and noticed there are many more changes to the Ampache5 API than I thought. Currently this is not working correctly, so you should downgrade to Ampache4 if possible. 

The Media Error Occurred is most likely due to the Current Playlist that is partially loaded due to the update. If you are able to start the playlist again from the menu, it should be solved. 

I will check what I can do short-term to fix the problem with Ampache5 compatibility!

**Comment by lachlan-00** [comment]
multi api support is just in Ampache develop and will be releasing with 5.2.0

**Comment by memen45** [comment]
@lemieuxl Were you able to try the new Ampache 5.20 and verify it's working?

**Comment by lemieuxl** [comment]
I'll try 5.2.0 once it's released (as it's easier for me to use the released archive which contains all dependencies).
I'll let you know.

**Comment by lachlan-00** [comment]
if anyone wants to test https://develop.ampache.dev/ follows the latest branch and user/pass is demo/demodemo

**Comment by lemieuxl** [comment]
I successfully synched a small playlist from the development server (https://develop.ampache.dev/) with SubMusic version 0.1.23. It was slower than normal though (I'm guessing because it's a slower server than what I'm used too).

If it's OK, I'll wait for the official 5.2.0 release before closing this issue.

**Comment by lachlan-00** [comment]
5.2.0 is out now
https://github.com/ampache/ampache/releases/tag/5.2.0

**Comment by lemieuxl** [comment]
Sync works with the official 5.2.0 release.
Thanks!
