### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by vanillanesquik** [memen45/SubMusic#36]
I am trying to connect my new Garmin Fenix 6X to my Airsonic server running on an unRAID docker.

I currently use the Audinaut app on my Android and I am able to fully connect to the server (HTTPS) address, username, and password. 

To connect on that app, I turn off the token/salt authentication.

When I use the same server address, username, and password that is working on that app, I continue to get API errors (Unknown).

Do you know how I may be able to troubleshoot this?

My Airsonic has the credentials set for BCRYPT if that makes any difference. Do I need a different set of credentials to work with Submusic?

Thanks!

**Comment by memen45** [comment]
Thanks for your report! Did you add `/rest` to your url? SubMusic adds this part of the url itself, so you can remove it from the 'server address' settings. 
Credentials are not encrypted (except it is sent over https when chosen), so the bcrypt setting might cause an issue (I never heard of this option within the Subsonic API spec). The server should however return some error code to the watch, so that is weird in itself then. 

If you want to, I can debug against your server to obtain more detailed logs. Just send some temporary login details through the 'Contact developer' option.

**Comment by memen45** [comment]
Your server responses are not following the Subsonic API specification completely. Not sure whether it only happens when there are no playlists/podcasts available, so you might want to test whether the error goes away by adding playlists to the server. 

For now, I have fixed the 'null / Unknown' error, it will be 'BAD_RESPONSE' in future version.

The specific issue is in the response structure. For the getPlaylists endpoint, SubMusic expects a response JSON with `{ subsonic-response: { playlists: { playlist: [{}, ...] } } }`, where playlist is tested to be an Array. From your server the response is `{ subsonic-response: { playlists: {  } } }`, so missing the playlist item. 

Which server software are you using? Could it be related to airsonic being replaced by airsonic-advanced currently?

**Comment by paulgking** [comment]
It is this on AirSonic (not sure on airsonic-advanced), same will happen with poscasts. Setting up a playlist will resolve the first part of the test, and if it's in place should make the other stuff work just fine.

**Comment by paulgking** [comment]
Just installed airsonic-advanced in docker, and it behaves the same:

{"subsonic-response" : {"status" : "ok","version" : "1.15.0","playlists" : {}}}

**Comment by vanillanesquik** [comment]
I wanted to confirm that I am running the binhex airsonic-advanced container on unraid.

I tried adding a test playlist but I was receiving the same API error.

Do I need to have both podcasts and playlist available for the server to sync correctly?

Paul- are you saying that your configuration is working correctly? 

Thanks

**Comment by memen45** [comment]
Thanks for your feedback @paulgking @vanillanesquik. I just updated the app to default to empty playlist instead of reporting the error. Also, I opened an issue: airsonic-advanced/airsonic-advanced#665.

Let me know if the error is resolved!
