### ISSUE TITLE
Support for Navidrome

### ISSUE THREAD

**Issue by morbificagent** [memen45/SubMusic#37]
Hi there,

I am using Navidrome which is a subsonic clone and has an api which is compatible to all subsonic players like dsub on my android.

But with submusic I only get the errormessage shown after selecting a Playlist and then try to show its songs or sync it:
![20211130_144937.jpg](https://user-images.githubusercontent.com/50199132/144059802-52950735-87b8-47f2-8e93-36c13d91e032.jpg)

**Comment by memen45** [comment]
This is due to both 
- limitation of the Subsonic API (it is only possible to request the full playlist details including all songs metadata)
- limitation of the Garmin watches for the response size of the requests

You can only effectively address the first cause by either
- change the server and set backend to Ampache API (Ampache API supports paged responses, and SubMusic will request smaller pages automatically)
- remove songs from the playlist until the error goes away (typically around 20 songs is the limit, but it depends on the metadata)
- split the songs in multiple playlists where each playlist is not too large (use Play All option to play from the split playlists at the same time)

**Comment by memen45** [comment]
Does Navidrome have additional API features?

**Comment by morbificagent** [comment]
Many thanks!

Splitting the songs in multiple playlists does work. For sure its a pain for bigger playlists but if these are limitations of the subsonic api you can't do anything against this for sure.

And no i don't think navidrome has another api.
