### ISSUE TITLE
Sync updated playlist problem

### ISSUE THREAD

**Issue by cristianpb** [memen45/SubMusic#49]
Hello 👋

First, thanks again for this app.

I use navidrone in my local server. Inside, I have a playlist with 20 songs which I update regularly with different songs.

The first time I upload the playlist to the watch everything goes flawlessly but when I want to update the playlist with different songs, then the submusic crashes and I can't use it anymore. I'm forced to delete the app, put the configuration and then sync my playlist again in the watch. 

I've seen the same behavior in two watches so I think maybe it's a bug.

Best regards,

**Comment by memen45** [comment]
Thanks for your feedback! It is not completely clear to me what steps you took and what exactly the behaviour is, so below some questions.

Are you able to access the SubMusic menu after the crash? Cause it should always be possible to enter the SubMusic menu, then choose About, Settings, Remove All Data, instead of completely reinstalling the whole app.

Normally, an error during sync should not cause any more issues apart from failing the sync. Could you show the minimum steps to reproduce the issue?

Did you try to e.g. remove a single song from the playlist, then open SubMusic on the watch and perform the sync? Does it give the same error?

Looking forward to hearing from you!

**Comment by cristianpb** [comment]
During my error I wasn't able to open SubMusic menu, I received an error message when accessing the app in the watch.

Right now, I'm trying to reproduce the error but I haven't found the step that make the update crash.

These are the steps that I have tried:

* Installing Submusic
* Selecting playlist
* Sync submusic
* Play music from the playlist
* Change songs from the playlist in the server (adding new songs and removing existing ones)
* Sync submusic
* Play new music

Maybe it's related with some time stamp. I'll try to do the same in a couple of days.

I will close the issue and reopen it when I found the steps to reproduce the error.
