### ISSUE TITLE
error 200

### ISSUE THREAD

**Issue by Vendo232** [memen45/SubMusic#5]
Hi

I`m using Nextloud, downloaded couple MP3 podcasts, followed your guide.
Connect on my watch Garmin 5 PLus , can see and check my playlists and then when I want to synch it gives me blank screen with "200"

my link to ampache is http://.... although the web I access nextcloud through is https:// 

any idea what to do?

**Comment by memen45** [comment]
Have you tried the 'Test Server' option on the watch? This option provides more information when an error occurs. 

It is weird that you are getting an http address in the nextcloud while accessing it from https. Did you setup the redirect properly? As far as I know http access should work, but if you have https available I would recommend using https.

**Comment by Vendo232** [comment]
I got Test Succeeded, then sync  gives me "200"

**Comment by memen45** [comment]
Thanks for testing. I noticed that the error checking during sync is more strict than for the Test Server option. Therefore, the test probably crashes upon retrieving the playlist songs from the Ampache backend and does not show the actual error. Error 200 indicates that the server responded, however the response is either malformed or reports an Ampache error. 
Which version of nextcloud and nextcloud music are you using?

**Comment by Vendo232** [comment]
Im using the latest, just installed it today, but while browsing through Nextcloud found a warning that my reverse proxy is not resolved and that is creating the htrp/htrps issue. It seems the problem is my setup , will have to debug

**Comment by memen45** [comment]
Inlog OK with half circle would indicate the server never responds to playlist_songs action. Or the response is filtered by the watch software and the callback does not occur. Since it is throwing an error during the sync, I suspect there is something wrong with the response. I am currently working on an update, so I will try and finish that before I can debug on an updated nextcloud music (0.16).

**Comment by memen45** [comment]
I have just checked and my server actually runs the latest version of nextcloud music (v0.16) and it is working smoothly with the SubMusic app. Therefore I think the problem is with your setup. If you are able to provide me (privately) with some temporary login, I could debug the problem in more detail in the simulator.

It is interesting to see that you are actually able to retrieve the list of playlists, but not the playlist songs. 
- Have you checked your server logs regarding errors from the music app? 
- Have you tried other Ampache clients on the same server?
- What file types do you use (currently only mp3s are requested from the server, others are skipped)? 
- Do you have long names or weird characters in the titles? Do you use self-signed certificates? Those are not supported by Garmin software.

Thanks in advance for sharing your findings.

**Comment by Vendo232** [comment]
May I ask you, if you have time to check if you could reproduce my issues?

![image](https://user-images.githubusercontent.com/44098230/94995665-f924ca00-055c-11eb-8a54-fd1186e2967c.png)

I`m getting error in logg, not sure what it means

`[PHP] Error: fseek(): stream does not support seeking at /var/www/html/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#82

GET /apps/music/api/album/48/cover
from 73.181.52.166 by admin at 2020-10-03T15:42:29+00:00`

**Comment by memen45** [comment]
I just tested on your server and indeed get to the Login OK. I found that some of the metadata is null, and therefore an exception is thrown when trying to convert the null to a number. First, this is a bug that has been reported [here](https://github.com/owncloud/music/issues/670), and is indeed related to your external SMB storage. Please check in on that issue to get the root cause solved. Secondly, I can fix the problem by checking for null values on the response. It can take a few days, since I am simultaneously working on some larger rework of the app. 

Other (open source) solutions you can use to connect to are Ampache/Ampache, AirSonic and (closed source) Subsonic.

**Comment by Vendo232** [comment]
I have tried AirSonic and it did not work, Ampache using Ampache API appeared it is working, I was able to synch playlist and it showed lenght under the playlist but could not make it play.

Because I was not able to setup shared folder to work with Nextcloud other than SMB this is probably dead end for me.

Thank you for your effort and help.

**Comment by memen45** [comment]
For Airsonic you need to change the backend in the settings to Subsonic API, as well as the url to the correct one. 

With the Ampache API backend, were you able to select the playlist for playback? Or is the music player still empty?

Up until now, I have not received any reports that the app is not working with either Airsonic or Ampache. Your problem with SMB is one I can and will address in the next update, however the other two solutions should just work if you use a default setup and the correct settings. If you need specific help that is unrelated to this issue, you can use the contact developer option [in the Garmin app store](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794).

If it is okay with you, I will leave this issue opened until v0.0.16 is available.

**Comment by Vendo232** [comment]
Would you be able to advise where is the API setting in Airsonic, I was not able to find it

**Comment by memen45** [comment]
Airsonic implements the Subsonic API, so you need to go to the connect iq app, open the SubMusic app page, go to settings and then change the first setting 'API backend' to Subsonic API. Also change the url to the url that you use in the browser to open the Airsonic web page, and of course login name and password.

**Comment by Vendo232** [comment]
ohh, I did that, the same I did use for Ampache. tried Ampache and Subsonic API in the IQ Subsonic app Setting. Used my HTTPS://XYZ Domain I use to connect to Ampache and Subsonic. Used Login and Password to get to the Ampache and Subsonic. 

Let me do it again and write down the error codes for each way

**Comment by memen45** [comment]
Thanks for the update! 

The wifi speed is very low on watch devices, so if you try to sync such a large file, it may take a while. For normal length songs (3 mins, 4 MB) it might already take up to a minute, so for lengthy podcasts (190 mins, ~240 MB?) it might take a long time to sync. I cannot find the size limits for audio files, so that would need some testing to find out. 

Airsonic
-  with Subsonic backend: should work, percentages are not yet accurate though and as far as I know, downloads cannot be interrupted and continued later.
-  with Ampache backend: should not work.
Ampache
- with Subsonic backend: should work, did you check and update the url accordingly?
- with Ampache backend: I have no idea why the Ampache backend sync would finish immediately, as the requests should return the same response from the server as with AirSonic/Subsonic combination.

**Comment by memen45** [comment]
Hi,

The update was released just now. It addresses some problems you mentioned here as well (e.g. the Nextcloud external storage bug), so let me know if it works better now. Download times will still be low though, due to watch limitations. 

Best regards,

**Comment by Vendo232** [comment]
Hello, great news, will give it a try tomorrow and will report back.

**Comment by memen45** [comment]
According to #6, the sync of a single podcast can take up to 6 minutes. In the meantime, the progress will not update, so it might look like it is not working.
