### ISSUE TITLE
Cannot remove data from watch "remove data" screen

### ISSUE THREAD

**Issue by thekiefs** [memen45/SubMusic#61]
I'm trying to clear my watch and retry syncing since a lot of songs aren't playing. 

After removing the data I go back into the Music settings and see that all the settings remained the same and the playlists / songs are stills showing.

**Comment by memen45** [comment]
Have checked the error logs, but I do not see one for your device.
https://github.com/memen45/SubMusic/blob/bd76a1907933c745d439753af6bc535a272c69fe/source/View/SubMusicMenuAboutSettings.mc#L119-L129

Does the app close after removing the content? Did you try to uninstall/reinstall afterwards? It may also be related to the missing phone connection (the watch software is quite unreliable).

**Comment by memen45** [comment]
I just tried, and found that the app does not exit after removing the data (probably a Garmin bug). However, you can close the app by opening Garmin settings, then choose a different Music Provider. Then change back to SubMusic. 

That does not explain the 10GB of storage still left in the device though.

**Comment by thekiefs** [comment]
Yeah, I did that and still have the storage problem. Is this a Garmin bug?

**Comment by memen45** [comment]
As far as I can see, yes. However, I have not verified your results with Garmin Express software (could not get it to work at first, and now I am not running windows anymore). 

I found some stats that I could use to display used memory from within SubMusic. That way we could verify the Garmin Express results. 

Unfortunately, due to [this bug](https://forums.garmin.com/developer/connect-iq/i/bug-reports/bug-makewebrequest-returns-unknown_error-when-in-simulator-media-mode-sync), I have not been able to test new versions of the app, so I will have to wait for this to be solved before I can add the usedMemory indication.

**Comment by memen45** [comment]
The memory and cache usage can now be checked in the watch settings. Go to Settings > Storage to find Memory (app metadata used) and Media Cache (the size of all the music files. Also, the menus should reload now after "remove data" option (and other menu operations. 

Hope this helps. Let me know your new insights with this feature in relation to your issue here!

**Comment by memen45** [comment]
Above changes can be found in app version 0.2.7-perieres, should be in Connect IQ app store now.

**Comment by thekiefs** [comment]
Awesome! The in-app button works great. 

There's still a discrepancy with the Garmin Express app (see screenshot) and the Storage > Media Cache on phone (shows 52MB), but seems like more of a Garmin Express issue (it's still unclear what the 10.5GB is for) rather than SubMusic so I'll close this for now.

<img width="628" alt="Screen Shot 2022-12-26 at 21 50 50" src="https://user-images.githubusercontent.com/51860580/209618184-9dccdddc-b265-4e77-8380-e9e141e19eb9.png">

**Comment by memen45** [comment]
Nice! Indeed it is most likely Garmin watch or Garmin Express bug based on this info. Thanks a lot for reporting the issue!
