### ISSUE TITLE
Plex - Application stuck at syncing

### ISSUE THREAD

**Issue by Visualflea** [memen45/SubMusic#66]
Apologies if this isn't the appropriate place to report this issue.  

I believe that I have the correct settings for the application:

- API Backend = Plex API
- Server Address = https://myreverseproxyplexaddress.com (points to port 443)
- Username = myplexusername@email.com
- API Key = apikeystring
- Authentication Method = API
- Enable Skip = Yes

I'm able to browse and select the playlists that i want to sync.  The application on my Fenix 6 hangs at sync (and drains the battery fast).
Test Server option never completes, it hangs at 0 podcasts. 

Plex site states that my api is temporary, should I pursue instructions on getting a persistent API key?

Also wanted to thank you for developing this app and thinking of Plex!!  If i can get this working, I'll get a ton of use out of it.

Thanks,
Justin

**Comment by memen45** [comment]
Hi Justin,

Thanks for your feedback! Did you check your WiFi networks are correctly setup? During browsing, the watch connects through the phone. During sync, the watch will connect to a WiFi network that you set up before (watch settings, Wi-Fi, connect to WiFi to check).

Since you do not get any error, other option would be to reboot the watch. I will check the crash logs later for your device!

Best regards,

**Comment by memen45** [comment]
Just checked the error logs, but I do not see any errors related to your device today/yesterday.
