### ISSUE TITLE
PLEX - No playlists?

### ISSUE THREAD

**Issue by MRFU510N88** [memen45/SubMusic#77]
Hi I have connected to my plex server using address and API Key. When I go to sync playlists or browse playlists there arent any? I created a new playlist with just 1 song and that still doesnt appear.

Any help appreciated or is this a current bug?

**Comment by memen45** [comment]
As far as I know, Plex is fully working. It might be related to the playlist type. Is it set to audio? All playlists other than type 'audio' are filtered, as videos cannot be played on the watch.

**Comment by MRFU510N88** [comment]
I am getting garmin SDK error 300 and network request timed out error when I initiate server test on the watch.

Likely due to this part: https://ip-adress.somehashvalue.plex.direct:32400/

Unless I am looking in the wrong place your guide only appears to cover how to retrieve the API token (via a plex official guide: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

How do you retrieve the "somehashvalue are unique for your situation".

This would likely be where my problem lies.

**Comment by memen45** [comment]
The screenshot in step 3 in the linked article shows a url as well! So the same place where you find the token, you should also find the full url, including the 'somehashvalue'. 

The error -300 usually indicates an issue with HTTPS certificates. It might be that you forgot the s in https:// in the url, or you might need to setup a reverse proxy to serve Plex at port 443 instead of 32400. #33
https://github.com/memen45/SubMusic/issues/33#issuecomment-1200931272

**Comment by celery-4** [comment]
Exactly what part in that screenshot are you calling "some hash". I'm confused because the links between that screenshot and your instructions aren't lining up.

**Comment by memen45** [comment]
Ah, I see. The screenshot in the guide is showing a local IP address. This might work, but in many cases http addresses are not sufficient. You will get a different URL when you
- enable remote access in your Plex settings
- login through plex.tv, not your local IP address

And then follow the guide. In this case you will see the https url with the somehashvalue part. That will be the one you need.

Hope this helps!
