### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by leftsock** [memen45/SubMusic#91]
Context: New user for both Plex and Garmin. I'm tech savvy, but am not familiar with all the terms you're throwing around in the documentation.

For example:
> How to set up
>You need a music server supporting either the Ampache API or the Subsonic API

I have no clue whether this is true, but I have Plex, which is listed below, so I assume yes?

>and a compatible Garmin Watch

Forerunner 745, so yes.

From my phone, I found and installed the app, but now what?

> Plex... Should be supported now including transcoding. Make sure you enable remote access inside Plex

Documentation would help.

>then login through plex.tv and follow [these instructions](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/) to obtain the server address and the API key.

Done.

>Now head to Connect IQ app store, choose Plex API in the SubMusic app settings and fill in the Server Address and API key you found.

Specifics will help greatly here.

Oh, now that I think about it, I had poked at it first on the watch, but then it transitioned to my phone, and while I vaguely recall I skipped a field during setup. I presume that's where my key is supposed to go... I can't edit it after the fact? or even view it? or delete it so I can re-add it? This is where I'm stuck at.

Also, move the install instructions top and center, since they are complicated. Too many of your bad garmin reviews are because the instructions are at the bottom. Humans are bad at reading; putting it at the bottom is making this problem worse.

**Comment by memen45** [comment]
Hi, thanks for your feedback! 

In case you'd like to have an easier setup, you can choose the new '[SubMusic for Plex](https://apps.garmin.com/en-US/apps/30c6b7ab-7fc8-4241-99f5-9872dfe56a73)' app now available in the Connect IQ app store. Connection is setup automatically, without any settings or tokens to be copied, just a single login through your phone. If anything is unclear, feel free to use the 'Contact Developer' option [here](https://apps.garmin.com/en-US/apps/30c6b7ab-7fc8-4241-99f5-9872dfe56a73)!

With regards to [SubMusic](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794) itself, please note it is provided for free for now. You can see it as a very versatile tool, that works with many different servers and APIs, and Plex happens to be one of them.

- The first quoted sentence should indeed include the Plex API by now. This was formerly not supported, so therefore it wasn't listed.
- if you are unsure about how to enable remote access on your Plex server, please refer to the documentation of Plex. Google 'enable remote access in Plex' and you will find exactly what you need!
- You can always edit app settings, and you have to in order to properly connect to your personal server. SubMusic doesn't know the type, location or login details for your specific server. In order to change the settings, you have to open the Connect IQ app store on your phone, open the SubMusic app page and you will find a large 'Settings' button. 
- There are setup instructions for four different server APIs. One of them would have to come last, right? Plex support came last, so you will find it at the bottom of the instructions. I cannot put all instructions at the top :wink:

Hope the above helps. If you have any questions, let me know! Happy to help :smiley:

**Comment by leftsock** [comment]
I was installing "SubMusic for Plex" on the Garmin app store. 

Update: Before your reply, I uninstalled, then reinstalled, and now the watch doesn't do anything but blink and return to the watch face when I long press the "start music" button. I can't get it to start at all anymore.

>The first quoted sentence should indeed include the Plex API by now. This was formerly not supported, so therefore it wasn't listed.

The Garmin App Store link to this github installation documentation doesn't mention that I should not follow the instructions under "Plex". Hm, the garmin store descriptions seem to have been updated. Are the files here in github so I can suggest edits to make them clearer?

>if you are unsure about how to enable remote access on your Plex server, please refer to the documentation of Plex. Google 'enable remote access in Plex' and you will find exactly what you need!

Users are dumb/demanding these days. I recommend providing a link, even if it is for that exact search on google.

>You can always edit app settings, and you have to in order to properly connect to your personal server. SubMusic doesn't know the type, location or login details for your specific server. In order to change the settings, you have to open the Connect IQ app store on your phone, open the SubMusic app page and you will find a large 'Settings' button.

The only settings I see are
@SubMusic.String.skip_30s
@SubMusic.Strings.debug
but nowhere to enter the url for my plex server.

>There are setup instructions for four different server APIs. One of them would have to come last, right? Plex support came last, so you will find it at the bottom of the instructions. I cannot put all instructions at the top 😉

My point is more that if the (old) setup required you to do things like find an API key, the link to the instructions from the garmin "app store" should be front and center, not at the end. I tried configuring it from the watch/phone without reading the docs, and without an api key, I would've been stuck/confused. Better to label "must read these instructions".

**Comment by memen45** [comment]
If you are trying to get SubMusic for Plex working on your device, use the Contact Developer option on the Connect IQ app store.

The documentation for SubMusic does **not** apply to SubMusic for Plex.
