### ISSUE TITLE
Novice user here. Fenix 7x owner. 

### ISSUE THREAD

**Issue by FDBCF** [memen45/SubMusic#95]
Hello,

I have a fenix 7x watch.
I have an android smartphone.
I have a windows 11 desktop PC. 
I have a TrueNAS NAS on my LAN
I have a spare laptop to make a linux machine thing/server. (Might be needed to dedicate it as a media server or router?)
I have a spectrum router (model number: sax1v1s)

I want to play music from the NAS to the watch at home and ideally out in the world. I am not very tech inclined, but I can work my way through computer jargon. I am flexible with caching things on an SSD or HDD at this point on either the windows desktop PC or another dedicated server beyond the TrueNAS. 

I have managed to download subsonic from https://www.subsonic.org/pages/index.jsp
I have managed to load in a few music test files and get them to play locally on the my windows 11 computer. 
I have managed to find the network submenu in subsonic's settings and check off " Automatically configure your router to allow incoming connections to Subsonic (using UPnP or NAT-PMP port forwarding). " which yielded a " Status: Successfully forwarding port 4040. "

However as far as " Access your server over the Internet using an easy-to-remember address." I get a 
"Status: Could not connect to greenshirtcover2.subsonic.org. (ConnectTimeoutException) "

I don't know what that really means other than maybe my router not liking it and I have to do manual stuff which I am not familiar with. 

*Can anyone here please help me get this app going? I've been trouble shooting it for several hours. Any help is appreciated.*

**Comment by memen45** [comment]
If you want to sync more than 15-20 songs in a playlist, I would recommend Ampache instead of Subsonic! And if you are going to need file sharing in the future, Nextcloud might be even better (includes both Ampache and Subsonic, but also very reliable file server, calendar, contacts etc.). I have no experience with TrueNAS, but based on a Google search "Ampache on TrueNAS", it seems to be similar to normal server setup.

Making it accessible from outside the network is the challenging part. You need a domain name, DNS entry, and Apache or nginx to accept incoming traffic. Furthermore, most watches require https certificates as well. I found a guide for installing HTTPS certificates on a TrueNAS Nextcloud installation (would work the same for Ampache): [here](https://www.florian-rhomberg.net/2021/02/securing-nextcloud-jail-using-https-and-lets-encrypt-part-two/)

Hope this helps!

**Comment by FDBCF** [comment]
Hey, it's me again. I forgot to say I appreciate your timely response last time I was on this site. I've made some progress since last time. Is there any YouTube tutorial's you have on how the app works? I'm currently looking at the 0% complete screen when I hit sync. Not sure how long I should wait to see progress for just a few songs over the LAN wifi. I think this app has potential and I'm happy to donate something if I can get this all to work.

**Comment by memen45** [comment]
Could be various things. In the readme.md you can find common causes, e.g. custom port, missing https, etc.. Always first check if your server is available through a browser. 

If you want personal support, please send me a message through the 'Contact Developer' option on the SubMusic app page in Connect IQ. Please send any details regarding your server setup and app settings along, it helps a lot with debugging!

**Comment by FDBCF** [comment]
okay contacted you via the connectiq link, lemme know when if you don't get a quick reply within a few days or it didn't reach at all.

**Comment by memen45** [comment]
Closing as it's 2 months ago, if not resolved, please feel free to reopen!
